[build]
  command = 'yarn website:build'
  # publish = './packages/website/dist'
  publish = './packages/website/.next'

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://figma-export.netlify.app/*"
  to = "https://figma-export.marcomontalbano.com/:splat"
  force = true
