blank_issues_enabled: false
contact_links:
  - name: Website
    url: https://figma-export.marcomontalbano.com
    about: You can easily and automatically export your figma components and styles and use them directly into your website.
