name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Node 🧰
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Update npm 📦
        run: npm install -g npm@latest

      - name: Install 📦
        run: |
          yarn --immutable
          npm install -g @oclif/dev-cli

      - name: Build 🛠
        run: yarn build

      - name: Publish 🚀 PRERELEASE
        if: 'github.event.release.prerelease'
        run: ./node_modules/.bin/lerna publish from-git --dist-tag next --require-scripts --yes

      - name: Publish 🚀 PRODUCTION
        if: '!github.event.release.prerelease'
        run: ./node_modules/.bin/lerna publish from-git --require-scripts --yes
